/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Diseño;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pieri
 */
public class frmBannerEventos extends javax.swing.JFrame{
    JpInformes info;
    JpNuevoEvento nuevo = new JpNuevoEvento();
    JpBaseD base = new JpBaseD();
    

    /**
     * Creates new form frmBannerEventos
     */
    public frmBannerEventos() throws Exception {
        this.info = new JpInformes();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("LA CASA DEL MAESTRO");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        Main.add(nuevo);
        Main.add(info);
        Main.add(base);
        
        nuevo.setVisible(false);
        info.setVisible(false);
        base.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnBase = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnTablas = new javax.swing.JButton();
        Main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(0, 51, 102));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setText("Nuevo");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusPainted(false);
        btnAgregar.setFocusable(false);
        btnAgregar.setMaximumSize(new java.awt.Dimension(106, 39));
        btnAgregar.setMinimumSize(new java.awt.Dimension(106, 39));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btnBase.setBackground(new java.awt.Color(0, 51, 102));
        btnBase.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        btnBase.setForeground(new java.awt.Color(255, 255, 255));
        btnBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base.png"))); // NOI18N
        btnBase.setText("Base de datos");
        btnBase.setBorderPainted(false);
        btnBase.setFocusPainted(false);
        btnBase.setFocusable(false);
        btnBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseActionPerformed(evt);
            }
        });
        jPanel2.add(btnBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 51, 102));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setFocusable(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        btnTablas.setBackground(new java.awt.Color(0, 51, 102));
        btnTablas.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        btnTablas.setForeground(new java.awt.Color(255, 255, 255));
        btnTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        btnTablas.setText("Informes");
        btnTablas.setBorderPainted(false);
        btnTablas.setFocusPainted(false);
        btnTablas.setFocusable(false);
        btnTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablasActionPerformed(evt);
            }
        });
        jPanel2.add(btnTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new java.awt.CardLayout());
        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        nuevo.setVisible(true);
        info.setVisible(false);
        base.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseActionPerformed
        // TODO add your handling code here:
        nuevo.setVisible(false);
        info.setVisible(false);
        base.setVisible(true);
    }//GEN-LAST:event_btnBaseActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        String botones [] = {"Salir","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea salir?", "La casa del maestro", 0, 0, null, botones, this);
        if(eleccion==JOptionPane.YES_OPTION){
            frmSelect fSel = new frmSelect();
            fSel.setVisible(true);
            this.dispose();
        }else{
            JpNuevo JpN = new JpNuevo();
            JpN.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablasActionPerformed
        // TODO add your handling code here:
        nuevo.setVisible(false);
        info.setVisible(true);
        base.setVisible(false);
    }//GEN-LAST:event_btnTablasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBannerEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBannerEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBannerEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBannerEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmBannerEventos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmBannerEventos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBase;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTablas;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
