/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Diseño;

import DAO.EventoDAO;
import Entidades.Evento;
import Entidades.Mensual;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pieri
 */
public class JpBaseD extends javax.swing.JPanel {
    EventoDAO p1 = new EventoDAO();
    /**
     * Creates new form JpBaseD
     */
    public JpBaseD() {
        initComponents();
        ButtonGroup btnMes = new ButtonGroup();
        
        btnMes.add(rbEnero);
        btnMes.add(rbFebrero);
        btnMes.add(rbMarzo);
        btnMes.add(rbAbril);
        btnMes.add(rbMayo);
        btnMes.add(rbJunio);
        btnMes.add(rbJulio);
        btnMes.add(rbAgosto);
        btnMes.add(rbSeptiembre);
        btnMes.add(rbOctubre);
        btnMes.add(rbNoviembre);
        btnMes.add(rbDiciembre);
    }
    
    //TABLA MENSUAL
    private void modeloTablaPagoM( ArrayList Eventos){
        DefaultTableModel tabla1 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int colum){
                return false;
            }
        };
        
        tabla1.setRowCount(Eventos.size());
        tabla1.addColumn("DNI");
        tabla1.addColumn("Organizador");
        tabla1.addColumn("Evento");
        tabla1.addColumn("F. Evento");
        tabla1.addColumn("F.Reservación");
        tabla1.addColumn("Precio");
        
        for (int i=0; i<Eventos.size(); i++){
            Evento b = (Evento) Eventos.get(i);
            tabla1.setValueAt(b.getDniOrg(), i,0);
            tabla1.setValueAt(b.getNombreOrg(), i, 1);
            tabla1.setValueAt(b.getNombreEvento(), i, 2);
            tabla1.setValueAt(b.getFechaEvento(), i, 3);
            tabla1.setValueAt(b.getFechaIngreso(), i, 4);
            tabla1.setValueAt(b.getPrecioEvento(), i, 5);
        }
        
        tblEventos.setModel(tabla1);
        CentrarDatosPagos(tblEventos);
    }
    
    public void llenarTablaMensual() throws Exception{
        int mesC = 0;
        if(rbEnero.isSelected()){
                    mesC=1;
                }
                if(rbFebrero.isSelected()){
                    mesC=2;
                }
                if(rbMarzo.isSelected()){
                    mesC=3;
                }
                if(rbAbril.isSelected()){
                    mesC=4;
                }
                if(rbMayo.isSelected()){
                    mesC=5;
                }
                if(rbJunio.isSelected()){
                    mesC=6;
                }
                if(rbJulio.isSelected()){
                    mesC=7;
                }
                if(rbAgosto.isSelected()){
                    mesC=8;
                }
                if(rbSeptiembre.isSelected()){
                    mesC=9;
                }
                if(rbOctubre.isSelected()){
                    mesC=10;
                }
                if(rbNoviembre.isSelected()){
                    mesC=11;
                }
                if(rbDiciembre.isSelected()){
                    mesC=12;
                } 
        ArrayList<Evento> lista2;
        lista2 = p1.listaEventosB(txtAño.getText(),mesC);
        modeloTablaPagoM(lista2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        javax.swing.JButton btnBuscar = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelMeses = new javax.swing.JPanel();
        rbDiciembre = new javax.swing.JRadioButton();
        rbJulio = new javax.swing.JRadioButton();
        rbNoviembre = new javax.swing.JRadioButton();
        rbFebrero = new javax.swing.JRadioButton();
        rbEnero = new javax.swing.JRadioButton();
        rbAbril = new javax.swing.JRadioButton();
        rbMarzo = new javax.swing.JRadioButton();
        rbMayo = new javax.swing.JRadioButton();
        rbJunio = new javax.swing.JRadioButton();
        rbOctubre = new javax.swing.JRadioButton();
        rbSeptiembre = new javax.swing.JRadioButton();
        rbAgosto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("BASE DE REGISTRO DE EVENTOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEventos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 840, 270));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.setFocusPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, 30));
        add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 140, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Selecciona mes:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, 30));

        panelMeses.setBackground(new java.awt.Color(255, 255, 255));
        panelMeses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbDiciembre.setBackground(new java.awt.Color(255, 255, 255));
        rbDiciembre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDiciembre.setText("Diciembre");
        rbDiciembre.setFocusPainted(false);
        rbDiciembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiciembreActionPerformed(evt);
            }
        });
        panelMeses.add(rbDiciembre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        rbJulio.setBackground(new java.awt.Color(255, 255, 255));
        rbJulio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbJulio.setText("Julio");
        rbJulio.setFocusPainted(false);
        rbJulio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJulioActionPerformed(evt);
            }
        });
        panelMeses.add(rbJulio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 30));

        rbNoviembre.setBackground(new java.awt.Color(255, 255, 255));
        rbNoviembre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNoviembre.setText("Noviembre");
        rbNoviembre.setFocusPainted(false);
        rbNoviembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoviembreActionPerformed(evt);
            }
        });
        panelMeses.add(rbNoviembre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 30));

        rbFebrero.setBackground(new java.awt.Color(255, 255, 255));
        rbFebrero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbFebrero.setText("Febrero");
        rbFebrero.setFocusPainted(false);
        rbFebrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFebreroActionPerformed(evt);
            }
        });
        panelMeses.add(rbFebrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        rbEnero.setBackground(new java.awt.Color(255, 255, 255));
        rbEnero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbEnero.setText("Enero");
        rbEnero.setFocusPainted(false);
        rbEnero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEneroActionPerformed(evt);
            }
        });
        panelMeses.add(rbEnero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        rbAbril.setBackground(new java.awt.Color(255, 255, 255));
        rbAbril.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAbril.setText("Abril");
        rbAbril.setFocusPainted(false);
        rbAbril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAbrilActionPerformed(evt);
            }
        });
        panelMeses.add(rbAbril, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

        rbMarzo.setBackground(new java.awt.Color(255, 255, 255));
        rbMarzo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbMarzo.setText("Marzo");
        rbMarzo.setFocusPainted(false);
        rbMarzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMarzoActionPerformed(evt);
            }
        });
        panelMeses.add(rbMarzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        rbMayo.setBackground(new java.awt.Color(255, 255, 255));
        rbMayo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbMayo.setText("Mayo");
        rbMayo.setFocusPainted(false);
        rbMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMayoActionPerformed(evt);
            }
        });
        panelMeses.add(rbMayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 30));

        rbJunio.setBackground(new java.awt.Color(255, 255, 255));
        rbJunio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbJunio.setText("Junio");
        rbJunio.setFocusPainted(false);
        rbJunio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJunioActionPerformed(evt);
            }
        });
        panelMeses.add(rbJunio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 30));

        rbOctubre.setBackground(new java.awt.Color(255, 255, 255));
        rbOctubre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbOctubre.setText("Octubre");
        rbOctubre.setFocusPainted(false);
        rbOctubre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOctubreActionPerformed(evt);
            }
        });
        panelMeses.add(rbOctubre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        rbSeptiembre.setBackground(new java.awt.Color(255, 255, 255));
        rbSeptiembre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbSeptiembre.setText("Septiembre");
        rbSeptiembre.setFocusPainted(false);
        rbSeptiembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeptiembreActionPerformed(evt);
            }
        });
        panelMeses.add(rbSeptiembre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 30));

        rbAgosto.setBackground(new java.awt.Color(255, 255, 255));
        rbAgosto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAgosto.setText("Agosto");
        rbAgosto.setFocusPainted(false);
        rbAgosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAgostoActionPerformed(evt);
            }
        });
        panelMeses.add(rbAgosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 30));

        add(panelMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 550, 70));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Año:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 33, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            llenarTablaMensual();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbDiciembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiciembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDiciembreActionPerformed

    private void rbJulioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJulioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJulioActionPerformed

    private void rbNoviembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoviembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNoviembreActionPerformed

    private void rbFebreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFebreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFebreroActionPerformed

    private void rbEneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEneroActionPerformed

    private void rbAbrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAbrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAbrilActionPerformed

    private void rbMarzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMarzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMarzoActionPerformed

    private void rbMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMayoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMayoActionPerformed

    private void rbJunioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJunioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJunioActionPerformed

    private void rbOctubreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOctubreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOctubreActionPerformed

    private void rbSeptiembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeptiembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSeptiembreActionPerformed

    private void rbAgostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAgostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAgostoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMeses;
    private javax.swing.JRadioButton rbAbril;
    private javax.swing.JRadioButton rbAgosto;
    private javax.swing.JRadioButton rbDiciembre;
    private javax.swing.JRadioButton rbEnero;
    private javax.swing.JRadioButton rbFebrero;
    private javax.swing.JRadioButton rbJulio;
    private javax.swing.JRadioButton rbJunio;
    private javax.swing.JRadioButton rbMarzo;
    private javax.swing.JRadioButton rbMayo;
    private javax.swing.JRadioButton rbNoviembre;
    private javax.swing.JRadioButton rbOctubre;
    private javax.swing.JRadioButton rbSeptiembre;
    private javax.swing.JTable tblEventos;
    private javax.swing.JTextField txtAño;
    // End of variables declaration//GEN-END:variables

    private void CentrarDatosPagos(JTable tblEventos) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
