/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Diseño;

import DAO.EventoDAO;
import java.text.SimpleDateFormat;
import java.util.Date; 
import javax.swing.JOptionPane;

/**
 *
 * @author pieri
 */
public class JpNuevoEvento extends javax.swing.JPanel {
    EventoDAO e1 = new EventoDAO();
    double precio;

    /**
     * Creates new form JpNuevoEvento
     */
    public JpNuevoEvento() {
        initComponents();
        
    }
    
    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatofecha.format(fecha);
    }
    
    public void Limpiar(){
        txtDniO.setText("");
        txtNombreE.setText("");
        txtNombreO.setText("");
        txtCalendario.setDateFormatString("");
        txtPrecio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCalendario = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtDniO = new javax.swing.JTextField();
        txtNombreO = new javax.swing.JTextField();
        txtNombreE = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        add(txtCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 260, 34));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("INGRESAR NUEVO EVENTO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Seleccionar fecha de evento");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 180, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Precio de alquiler:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Nombre de organizador (a):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Nombre del evento:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, -1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("DNI de organizador (a):");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, -1));

        txtPrecio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKeyReleased(evt);
            }
        });
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 260, 30));

        txtDniO.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtDniO.setForeground(new java.awt.Color(51, 51, 51));
        txtDniO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txtDniO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniOActionPerformed(evt);
            }
        });
        txtDniO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniOKeyReleased(evt);
            }
        });
        add(txtDniO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 260, 30));

        txtNombreO.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtNombreO.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txtNombreO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreOActionPerformed(evt);
            }
        });
        txtNombreO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreOKeyReleased(evt);
            }
        });
        add(txtNombreO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 260, 30));

        txtNombreE.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtNombreE.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txtNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEActionPerformed(evt);
            }
        });
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreEKeyReleased(evt);
            }
        });
        add(txtNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 260, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 130, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyReleased

    private void txtDniOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniOActionPerformed

    private void txtDniOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniOKeyReleased
        // TODO add your handling code here:
        try {
            if(e1.Busqueda(txtDniO.getText())==1){
                txtNombreO.setText(e1.BDnombres(txtDniO.getText()));
                txtNombreO.setEditable(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtDniOKeyReleased

    private void txtNombreOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreOActionPerformed

    private void txtNombreOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreOKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreOKeyReleased

    private void txtNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEActionPerformed

    private void txtNombreEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEKeyReleased

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String dniO=txtDniO.getText();
        String nombreO=txtNombreO.getText(); 
        String nombreE=txtNombreE.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd");
        String FechaE= sdf.format(txtCalendario.getDate()); 
        String fechaIns=fecha(); 
        int precio=Integer.parseInt(txtPrecio.getText());
        
        try {
            if(e1.FechaR(FechaE)==1){
                JOptionPane.showMessageDialog(null, "YA EXISTE UNA PROGRAMACIÓN CON ESTA FECHA");
            }else{
                if(e1.Busqueda(txtDniO.getText())==1){
                    double descuento=precio * 0.15;
                    double precioD=precio- descuento;
                    e1.registrar(dniO, nombreO, nombreE,FechaE, fechaIns, precioD);
                    Limpiar();
                    JOptionPane.showMessageDialog(null, "EL USUARIO ES SOCIO: -15%");
                }else{
                    e1.registrar(dniO, nombreO, nombreE,FechaE, fechaIns, precio);
                    Limpiar();
                }
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser txtCalendario;
    private javax.swing.JTextField txtDniO;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtNombreO;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
